name: CI/CD - Lint and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 1: Configurar Node.js e pnpm
      # Usa a ação setup-node para configurar o Node.js
      # E explicitamente informa para instalar o pnpm
      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a versão do Node.js que seu projeto utiliza
          cache: "pnpm" # Habilita o cache para o pnpm, o que acelera builds subsequentes

      # Passo 2: Instalar dependências com pnpm
      # Roda 'pnpm install'
      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile # '--frozen-lockfile' garante que o lockfile não seja modificado

      # Passo 3: Rodar ESLint com pnpm
      # Usa 'pnpm lint'
      - name: Run ESLint with pnpm
        run: pnpm lint

      # Passo 4: Rodar Testes Jest/RTL com pnpm
      # Usa 'pnpm test'
      - name: Run Tests with pnpm
        run: pnpm test
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3000/api

      # Opcional: Upload de resultados de cobertura de código
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/lcov.info
      #     verbose: true
